

export const coinIcons = {
    BTC: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1508609483/bitcoin_eqld4v.png',
    ETH: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1508609485/ethereum_nw0chu.png',
    XRP: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1508609486/ripple_p0xeut.png',
    BCH: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1516327336/bch_2x_hahroi.png',
    LTC: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1512427497/ltc_fjbqjf.png',
    DASH: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1508609484/dash_oltvqi.png',
    XEM: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1508609486/nem_imprip.png',
    BCC: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1508609486/bitconnect_oj1bo5.png',
    XMR: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1508609486/monero_wzk3ur.png',
    NEO: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1508609486/neo_fvoo6c.png',
    MIOTA: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1512510148/miota_2x_xkby9u.png',
    ADA: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1513434489/cardano_unympj.png',
    BTG: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1513434542/bitcoin-gold_reytam.png',
    XLM: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1516326886/xlm_2x_jfwlwt.png',
    ADA: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1516326874/ada_2x_g4fs0c.png',
    IOTA: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1516327102/miota_2x_zsvtqc.png',
    TRX: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1516326885/trx_2x_ukhxjm.png',
    EOS: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1516326878/eos_2x_dvr7p0.png',
};

// export const coinIcons = {
//     BTC: './../../node_modules/cryptocurrency-icons/dist/32@2x/color/btc.png',
//     ETH: './../../node_modules/cryptocurrency-icons/dist/32@2x/color/eth.png',
//     XRP: './../../node_modules/cryptocurrency-icons/dist/32@2x/color/xrp.png',
//     BCH: './../../node_modules/cryptocurrency-icons/dist/32@2x/color/bch.png',
//     LTC: './../../node_modules/cryptocurrency-icons/dist/32@2x/color/ltc.png',
//     DASH: './../../node_modules/cryptocurrency-icons/dist/32@2x/color/dash.png',
//     XEM: './../../node_modules/cryptocurrency-icons/dist/32@2x/color/xem.png',
//     BCC: './../../node_modules/cryptocurrency-icons/dist/32@2x/color/bcc.png',
//     XMR: './../../node_modules/cryptocurrency-icons/dist/32@2x/color/xmr.png',
//     NEO: './../../node_modules/cryptocurrency-icons/dist/32@2x/color/neo.png',
//     MIOTA: './../../node_modules/cryptocurrency-icons/dist/32@2x/color/miota.png',
//     ADA: './../../node_modules/cryptocurrency-icons/dist/32@2x/color/ada.png',
//     BTG: './../../node_modules/cryptocurrency-icons/dist/32@2x/color/btg.png',
//     XLM: './../../node_modules/cryptocurrency-icons/dist/32@2x/color/xlm.png',
//     ADA: './../../node_modules/cryptocurrency-icons/dist/32@2x/color/ada.png',
//     IOTA: './../../node_modules/cryptocurrency-icons/dist/32@2x/color/iota.png',
//     TRX: './../../node_modules/cryptocurrency-icons/dist/32@2x/color/trx.png',
//     EOS: './../../node_modules/cryptocurrency-icons/dist/32@2x/color/eos.png',
//     UDTA: './../../node_modules/cryptocurrency-icons/dist/32@2x/color/udta.png',
// };
